apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: example-cluster01
  namespace: default
spec:
  values:
    kafkaNodes: 3
    kafkaStoragePerNode: 50Gi
    kafkaUsers:
      - user1
      - user2
  kubeConfig:
    secretRef:
      name: example-tenant01-kubeconfig
  chart:
    spec:
      chart: ./charts/kaas
      version: "0.1.0"
      sourceRef:
        kind: GitRepository
        name: kaas
  install:
    remediation:
      retries: -1