apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: kaas
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: master
  url: https://github.com/danielm0hr/aws-kafka-as-a-service